M48
; DRILL file {KiCad 8.0.1} date 2025-05-08T07:15:36+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-08T07:15:36+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.200
%
G90
G05
T1
X-1.403Y26.472
X5.049Y40.985
X14.394Y28.122
T2
X4.0Y67.5
X4.0Y3.5
X125.9Y67.5
X125.9Y3.5
M30
